bump_version: null
lint:
  files_exist:
  files_unchanged:
  nextflow_config:
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Usman Rashid, Jason Shiller
  description: A Nextflow pipeline for single genome, phased genomes and pan-genome annotation.
  force: false
  is_nfcore: false
  name: genepal
  org: plant-food-research-open
  outdir: .
  skip_features:
    - igenomes
  version: 0.5.0dev
update: null
