channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.3.3
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-gt=0.11.0
  - conda-forge::r-gtextras=0.5.0
  - conda-forge::r-kableextra=1.4.0
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-stringr=1.5.1
  - conda-forge::r-tibble=3.2.1
  - conda-forge::r-tidyr=1.3.1
  - conda-forge::r-viridis=0.6.5
